### PR TITLE
Greek Book with ISBN

### PR DESCRIPTION
**Pull request by konkiourtidou**

### CODE REVIEW

**Comment by konkiourtidou** [comment]
I'm trying (lol)

Κωνσταντία Δ. Κιουρτίδου

Στις Δευ, 28 Ιουν 2021, 18:07 ο χρήστης Charles Severance <
***@***.***> έγραψε:

**Comment by konkiourtidou** [comment]
did your neon finish in first place after all?

Στις Δευ, 28 Ιουν 2021 στις 6:07 μ.μ., ο/η Charles Severance <
***@***.***> έγραψε:

**Comment by csev** [comment]
Yes - first place among the Neons - 24th place overall.   But it was nice to start and finish a race with no mechanical failures.   We have been doing this for three years and every race something breaks down and takes us off the track.  It is an endurance race and so sometimes you can fix it and get back on the track.   But this race was the first where were never out for a mechanical problem.  Which is the bigger deal.  The other Neons had little problems - they were better and faster but we had fewer problems and mis-steps.

**Comment by konkiourtidou** [comment]
Congratulations!!
Perhaps the rain helped you ... :)

Στις Δευ, 28 Ιουν 2021 στις 6:17 μ.μ., ο/η Charles Severance <
***@***.***> έγραψε:

**Comment by csev** [comment]
Yes - the first day was raining and the second day was dry and warm.  There were a lot more spin-outs on the first day and a lot more breakdowns on the second day.  Neither happened to us so we just kept racing.

**Comment by konkiourtidou** [comment]
Κωνσταντία Δ. Κιουρτίδου

Στις Δευ, 28 Ιουν 2021, 18:39 ο χρήστης Charles Severance <
***@***.***> έγραψε:

> Yes - the first day was raining and the second day was dry and warm.
>
When you say warm what temperature do you mean?

> There were a lot more spin-outs on the first day and a lot more breakdowns
> on the second day. Neither happened to us so we just kept racing.
>
your mechanics did a good job!

If you find the time could you please take a look on tsugi's connection
with classroom...!?
Please! 😇

>

**Pull request merged**
